[watch]
watch = ["../battlefield-core/", "../battlefield-api/"]

[serve]
port = 3000

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["tailwind", "--input", "./tailwind.css", "--output", ".out/tailwind.css"]
