name = "Field"
map = "field"
description = "A wide open field with nowhere to hide."

[modules]
core = "0.0.1"

[modules.setup_preset]
version = "0.0.1"

[modules.setup_preset.config.archetypes]
swordsman = { "core.turns" = 1, "core.health" = 10, "core.attack" = 2, "core.defense" = 0, "core.crit_chance" = 10 }

[[modules.setup_preset.config.entities]]
archetype = "swordsman"
components = { "core.position" = [0, 0] }

[[modules.setup_preset.config.entities]]
archetype = "swordsman"
components = { "core.position" = [9, 9] }
