name = "Field"
description = "An open field with nowhere to hide."

[modules]
core = "0.0.1"

[map]
tiles = [
    [{tile_type="p",territory="a"}, {tile_type="p",territory="a"}, {tile_type="p",territory="a"}, {tile_type="p",territory="a"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}],
    [{tile_type="p",territory="a"}, {tile_type="p",territory="a"}, {tile_type="p",territory="a"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}],
    [{tile_type="p",territory="a"}, {tile_type="p",territory="a"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}],
    [{tile_type="p",territory="a"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}],
    [{tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}],
    [{tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}],
    [{tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p",territory="b"}],
    [{tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p",territory="b"}, {tile_type="p",territory="b"}],
    [{tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p",territory="b"}, {tile_type="p",territory="b"}, {tile_type="p",territory="b"}],
    [{tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p"}, {tile_type="p",territory="b"}, {tile_type="p",territory="b"}, {tile_type="p",territory="b"}, {tile_type="p",territory="b"}],
]

[map.tile_types.p]
name = "Plains"
description = "Open grassy plains. Does not provide much cover."
