[package]
name = "battlefield-api"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "battlefield_api"

[dependencies]
json-patch = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
uuid = { version = "1.1", features = ["serde"] }
